// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRCeUHTubYJW1aPKjjf38HmWBCwKW27jY',
    appId: '1:1004452497562:web:2e8239025286cd3ac4f723',
    messagingSenderId: '1004452497562',
    projectId: 'thyecommercemobileapp',
    authDomain: 'thyecommercemobileapp.firebaseapp.com',
    storageBucket: 'thyecommercemobileapp.firebasestorage.app',
    measurementId: 'G-6S8VD38NCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNTo-8x3Wk3BQimWrU5hEga6Kcr4YnC0Q',
    appId: '1:1004452497562:android:28951b632b61612ec4f723',
    messagingSenderId: '1004452497562',
    projectId: 'thyecommercemobileapp',
    storageBucket: 'thyecommercemobileapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB17pHoNfyL8WNmFaS28EhIlqSOyKvuPtk',
    appId: '1:1004452497562:ios:30438ddedfcfaae8c4f723',
    messagingSenderId: '1004452497562',
    projectId: 'thyecommercemobileapp',
    storageBucket: 'thyecommercemobileapp.firebasestorage.app',
    iosBundleId: 'com.example.thyecommercemobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB17pHoNfyL8WNmFaS28EhIlqSOyKvuPtk',
    appId: '1:1004452497562:ios:30438ddedfcfaae8c4f723',
    messagingSenderId: '1004452497562',
    projectId: 'thyecommercemobileapp',
    storageBucket: 'thyecommercemobileapp.firebasestorage.app',
    iosBundleId: 'com.example.thyecommercemobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRCeUHTubYJW1aPKjjf38HmWBCwKW27jY',
    appId: '1:1004452497562:web:bd8a56a4d735ce34c4f723',
    messagingSenderId: '1004452497562',
    projectId: 'thyecommercemobileapp',
    authDomain: 'thyecommercemobileapp.firebaseapp.com',
    storageBucket: 'thyecommercemobileapp.firebasestorage.app',
    measurementId: 'G-GBDTP73JQ9',
  );
}
