import 'package:flutter/material.dart';
import 'dart:ui';

class AppModel {
  final String name, description, category, image;
  final double rating, price;
  final int review;
  final List<Color> fcolor;
  final List<String> size;
  bool isCheck;

  AppModel({
    required this.name,
    required this.description,
    required this.price,
    required this.category,
    required this.rating,
    required this.review,
    required this.size,
    required this.isCheck,
    required this.fcolor,
    required this.image,
  });
}

List<AppModel> fullModels = [
  AppModel(
    name: 'Oversized Fit Printed Mesh T-Shirt',
    description: 'description',
    price: 100,
    category: 'Women',
    rating: 343,
    review: 678,
    size: ['S', 'L', 'XXL'],
    isCheck: true,
    fcolor: [Colors.black, Colors.blue, Colors.red],
    image: 'assets/Model/girl.png',
  ),
  AppModel(
    name: 'Sony WF-1000XM5',
    description: 'Industry-leading noise cancellation',
    price: 299.99,
    category: 'Electronics',
    rating: 1892,
    review: 4532,
    size: ['One ', 'Size'],
    isCheck: false,
    fcolor: [Colors.black, Colors.grey.shade400],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Madewell Transport Tote',
    description: 'Full-grain leather with brass hardware',
    price: 198.00,
    category: 'Women',
    rating: 567,
    review: 1203,
    size: ['Regular', 'Large'],
    isCheck: false,
    fcolor: [Colors.brown.shade700, Colors.black, Colors.brown.shade300],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Apple Watch Series 9',
    description: 'Advanced health monitoring and fitness tracking',
    price: 399.00,
    category: 'Electronics',
    rating: 2045,
    review: 8921,
    size: ['41mm', '45mm'],
    isCheck: false,
    fcolor: [Colors.black, Colors.blue.shade700, Colors.pink.shade300],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Hermès Twilly Silk Scarf',
    description: 'Hand-rolled edges, 100% silk',
    price: 165.00,
    category: 'Women',
    rating: 342,
    review: 587,
    size: ['One Size'],
    isCheck: false,
    fcolor: [
      Colors.pink.shade300,
      Colors.orange.shade400,
      Colors.purple.shade200,
    ],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Vintage Washed Denim Jacket',
    description: 'Classic oversized denim jacket with distressed details',
    price: 89.99,
    category: 'Unisex',
    rating: 428,
    review: 912,
    size: ['S', 'M', 'L', 'XL'],
    isCheck: false,
    fcolor: [Colors.blue.shade800, Colors.black, Colors.grey.shade600],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Ultraboost 5.0 DNA Running Shoes',
    description: 'Responsive cushioning for high energy return',
    price: 180.00,
    category: 'Men',
    rating: 876,
    review: 2345,
    size: ['US 8', 'US 9', 'US 10', 'US 11'],
    isCheck: false,
    fcolor: [Colors.black, Colors.blueGrey, Colors.white],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Lululemon Align High-Rise Pant',
    description: 'Buttery-soft Nulu™ fabric with naked sensation',
    price: 98.00,
    category: 'Women',
    rating: 3245,
    review: 7892,
    size: ['XS', 'S', 'M', 'L'],
    isCheck: false,
    fcolor: [Colors.black, Colors.blueGrey.shade800, Colors.purple.shade700],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Lululemon Align High-Rise Pant',
    description: 'Buttery-soft Nulu™ fabric with naked sensation',
    price: 98.00,
    category: 'Women',
    rating: 3245,
    review: 7892,
    size: ['XS', 'S', 'M', 'L'],
    isCheck: false,
    fcolor: [Colors.black, Colors.blueGrey.shade800, Colors.purple.shade700],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Bonobos Non-Iron Dress Shirt',
    description: 'Wrinkle-resistant premium cotton',
    price: 88.00,
    category: 'Men',
    rating: 487,
    review: 1023,
    size: ['S', 'M', 'L', 'XL'],
    isCheck: false,
    fcolor: [Colors.white, Colors.blue.shade800, Colors.grey.shade400],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Canada Goose Expedition Parka',
    description: 'Arctic-grade down insulation for extreme cold',
    price: 1495.00,
    category: 'Unisex',
    rating: 892,
    review: 2345,
    size: ['XS', 'S', 'M', 'L', 'XL'],
    isCheck: false,
    fcolor: [Colors.black, Colors.blueGrey.shade800, Colors.red.shade700],
    image: 'assets/Model/sweater.jpg',
  ),
  AppModel(
    name: 'Ray-Ban Aviator Classic',
    description: 'Gold frame with green lenses',
    price: 153.00,
    category: 'Unisex',
    rating: 2876,
    review: 6543,
    size: ['Standard'],
    isCheck: false,
    fcolor: [Colors.amber.shade800, Colors.black, Colors.grey.shade600],
    image: 'assets/Model/sweater.jpg',
  ),
];
